task: detection

num_classes: 365

remap_mscoco_category: True

train_dataloader:
  type: DataLoader
  dataset:
    type: Objects365Detection
    img_folder: ./dataset/objects365_v1/train/
    ann_file: ./dataset/objects365_v1/annotations/objects365_train.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 4
  num_workers: 4
  drop_last: True


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoLVISDetection
    img_folder: ./dataset/coco/
    ann_file: ./dataset/lvis/lvis_v1_minival_inserted_image_name.json
    text_file: ./texts/lvis_v1_class_texts.json
    transforms:
      type: Compose
      ops: ~

  shuffle: False
  batch_size: 8
  num_workers: 4
  drop_last: False