__include__: [
  '../dataset/train_o365_val_lvis_minival.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/ov_rtdetr_r50vd.yml',
]

output_dir: ./output/ov_rtdetr_r50vd_6x_o365
