__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/ov_rtdetr_r50vd.yml',
]

output_dir: ./output/ov_rtdetr_r50vd_6x_coco
